version: '3'

services:
  app:
    build:
      context: packages/app
      dockerfile: ../../infrastructure/app/Dockerfile
    ports:
      - '5000:3000'
    environment:
      - API_BASE_URL=http://localhost:4000
  api_nginx:
    build: infrastructure/api_nginx
    links:
      - api:php
    depends_on:
      - api
    ports:
      - '4000:80'
  api:
    build:
      context: packages/api
      dockerfile: ../../infrastructure/api/Dockerfile
    command: './wait-for-it.sh db:3306 -- ash -c "php artisan migrate:fresh --seed && php-fpm"'
    depends_on:
      - db
    volumes:
      - ".env:/var/www/.env"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: rdio
      MYSQL_USER: rdio
      MYSQL_PASSWORD: secret
