version: '3'

services:
  app:
    build:
      context: .
      dockerfile: infrastructure/app/Dockerfile
    ports:
      - '3000:3000'
  api_nginx:
    build: infrastructure/api_nginx
    links:
      - api:php
    ports:
      - '8080:80'
  api:
    build:
      context: .
      dockerfile: infrastructure/api/Dockerfile
    command: './wait-for-it.sh db:3306 -- ash -c "php artisan migrate:fresh --seed && php-fpm"'
    depends_on:
      - db
    links:
      - icecast
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: rdio
      MYSQL_USER: rdio
      MYSQL_PASSWORD: secret
  icecast:
    image: moul/icecast
    environment:
      ICECAST_SOURCE_PASSWORD: hackme
      ICECAST_ADMIN_PASSWORD: hackme
      ICECAST_PASSWORD: hackme
      ICECAST_RELAY_PASSWORD: hackme
    ports:
      - '8000:8000'
